### ISSUE TITLE
I can't find the project document named "Design and Simulation of Drone Flight Control Using PID Controller Final.pdf"

### ISSUE THREAD

**Issue by lst1221** [Abudi-seid10/Design-and-Simulation-of-Drone-Flight-Control-Using-PID-Controller#1]
I can't find the project document named "Design and Simulation of Drone Flight Control Using PID Controller Final.pdf". Did the author forget to upload it?

**Comment by Abudi-seid10** [comment]
uploaded

https://github.com/Abudi-seid10/Design-and-Simulation-of-Drone-Flight-Control-Using-PID-Controller/blob/main/Design%20and%20Simulation%20of%20Drone%20Flight%20Control%20Using%20PID%20Controller%20Final.pdf
